version: "3.8"
services:
  node-app:
    container_name: ts-node
    build:
      context: .
      dockerfile: Dockerfile
    image: ts-node-docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
